# Generated by Django 5.1.5 on 2025-01-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='company_name',
            new_name='report_for',
        ),
    ]
