# Generated by Django 4.2.19 on 2025-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0001_squashed_0002_rename_company_name_report_report_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='nessus_scan_name',
            field=models.CharField(db_index=True, max_length=190),
        ),
    ]
