# Generated by Django 4.2.19 on 2025-02-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportgen', '0004_report_reporting_team_alter_report_client_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rt_contacts',
            field=models.ManyToManyField(help_text='A redteam contact has to be created before it can be selected.', to='reportgen.rtcontact'),
        ),
    ]
